version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Poh1!yu8.
      MYSQL_DATABASE: bank
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - springboot-mysql

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bank
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Poh1!yu8.
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - springboot-mysql

networks:
  springboot-mysql:
    driver: bridge